# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.10.12
_src_path: gh:dafyddj/copier-docker-build
container_registry: ghcr.io
image_authors: Dafydd Jones <4195158+dafyddj@users.noreply.github.com>
image_namespace: techneg-it
image_repo: ci-salt-minion
no_cache_filter: update
release_is_scheduled: true
repo_name: ci-salt-minion
repo_namespace: techneg-it
