name: Build & Publish

on:
  push:
    tags:
      - v*

jobs:
  gsv:
    name: Get Salt versions
    if: fromJSON(needs.should-run.outputs.should-run)
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      salt-versions: ${{ steps.get-salt-versions.outputs.salt-versions }}
    steps:
      - id: get-salt-versions
        uses: dafyddj/get-salt-versions@8985aa223728e283e2caa4441cf4706bdf04d9e9 # v3.4.11
  run-publish-workflow:
    name: Run `publish` workflow
    needs: gsv
    strategy:
      fail-fast: false
      matrix:
        distro-version:
          - 12-slim
          - 13-slim
        salt-version:
          - ${{ fromJSON(needs.gsv.outputs.salt-versions) }}
    uses: ./.github/workflows/libpublish.yml
    permissions:
      packages: write
    with:
      build-args: |
        DISTRO_VERSION=${{ matrix.distro-version }}
        SALT_VERSION=${{ matrix.salt-version }}
      image-namespace: techneg-it
      image-repo: ci-salt-minion
      labels: org.opencontainers.image.authors=Dafydd Jones <4195158+dafyddj@users.noreply.github.com>
      no-cache-filter: update
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
      registry-username: ${{ github.repository_owner }}
  report:
    name: Report success
    needs:
      - run-publish-workflow
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Update Healthchecks.io
        run: |
          if [ -n "${HC_UUID}" ]; then
            curl -fsS -m 10 --retry 5 -o /dev/null "https://hc-ping.com/${HC_UUID}"
          fi
        env:
          HC_UUID: ${{ secrets.HC_UUID }}
